db:
     python manage.py makemigrations
	 python manage.py migrate  
server:
     python manage.py  runserver
all:
     python manage.py makemigrations
	 python manage.py migrate  
     python manage.py  runserver 
make push
    ./sript.sh